main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/',  views.about, name='about'),
    path('pokemons/', views.pokemons_index, name='index'),
    path('pokemons/<int:pokemon_id>/', views.pokemons_detail, name='detail'),
    path('pokemons/create/', views.PokemonCreate.as_view(), name='pokemons_create'),
    path('pokemons/<int:pk>/update', views.PokemonUpdate.as_view(), name='pokemons_update'),
    path('pokemons/<int:pk>/delete', views.PokemonDelete.as_view(), name='pokemons_delete'),
    path('pokemons/<int:pokemon_id>/add_training/', views.add_training, name='add_training'),
    path('pokeballs/', views.PokeballList.as_view(), name='pokeballs_index'),
    path('pokeballs/<int:pk>/', views.PokeballDetail.as_view(), name='pokeballs_detail'),
    path('pokeballs/create/', views.PokeballCreate.as_view(), name='pokeballs_create'),
    path('pokeballs/<int:pk>/update/', views.PokeballUpdate.as_view(), name='pokeballs_update'),
    path('pokeballs/<int:pk>/delete/', views.PokeballDelete.as_view(), name='pokeballs_delete'),
    path('pokemons/<int:pokemon_id>/assoc_pokeball/<int:pokeball_id>/', views.assoc_pokeball, name='assoc_pokeball'),
    path('pokemons/<int:pokemon_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),

]

pokedex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.forms import IntegerField
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


HOURS = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('E', 'Evening'),
)

class Pokeball(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pokeballs_detail', kwargs={'pk': self.id})



class Pokemon(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    ability = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    pokeballs = models.ManyToManyField(Pokeball)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'pokemon_id': self.id})


class Training(models.Model):
    time = models.CharField(
        max_length=1,
        choices=HOURS,
        default=HOURS[0][0]
    )
    type = models.CharField(max_length=200)

    pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_time_display()}"



class Photo(models.Model):
    url = models.CharField(max_length=200)
    pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for pokemon_id: {self.pokemon_id} @{self.url}"
        

main_app/forms.py
from django.forms import ModelForm
from .models import Training

class TrainingForm(ModelForm):
    class Meta:
        model = Training
        fields = ['time', 'type']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Pokemon, Pokeball, Photo
from .forms import TrainingForm
import boto3
import uuid
import os


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def pokemons_index(request):
    pokemons = Pokemon.objects.all()
    return render(request, 'pokemon/index.html', {'pokemons': pokemons})


@login_required
def pokemons_detail(request, pokemon_id):
    pokemon = Pokemon.objects.get(id=pokemon_id)
    id_list = pokemon.pokeballs.all().values_list('id')
    pokeballs_pokemon_doesnt_have = Pokeball.objects.exclude(id__in=id_list)
    training_form = TrainingForm()
    return render(request, 'pokemon/detail.html', {
        'pokemon': pokemon, 'training_form': training_form, 'pokeballs': pokeballs_pokemon_doesnt_have
    })


@login_required
def add_training(request, pokemon_id):
    form = TrainingForm(request.POST)
    if form.is_valid():
        new_training = form.save(commit=False)
        new_training.pokemon_id = pokemon_id
        new_training.save()
        return redirect('detail', pokemon_id=pokemon_id)


@login_required
def assoc_pokeball(request, pokemon_id, pokeball_id):
    Pokemon.objects.get(id=pokemon_id).pokeballs.add(pokeball_id)
    return redirect('detail', pokemon_id=pokemon_id)



@login_required
def add_photo(request, pokemon_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, pokemon_id=pokemon_id)
        except Exception as e:
            print('An error occured uploading file to S3')
            print(e)
    return redirect('detail', pokemon_id=pokemon_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else: 
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)



class PokemonCreate(LoginRequiredMixin, CreateView):
    model = Pokemon
    fields = ['name', 'type', 'ability', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)


class PokemonUpdate(LoginRequiredMixin, UpdateView):
    model = Pokemon
    fields = ['type', 'ability', 'description']

class PokemonDelete(LoginRequiredMixin, DeleteView):
    model = Pokemon
    success_url = '/pokemons/'

class PokeballList(LoginRequiredMixin, ListView):
    model = Pokeball

class PokeballDetail(LoginRequiredMixin, DetailView):
    model = Pokeball

class PokeballCreate(LoginRequiredMixin, CreateView):
    model = Pokeball
    fields = '__all__'

class PokeballUpdate(LoginRequiredMixin, UpdateView):
    model = Pokeball
    fields = ['name', 'color']

class PokeballDelete(LoginRequiredMixin, DeleteView):
    model = Pokeball
    success_url = '/pokeballs/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About this Pokedex</h1>
    <p>The Pokédex is an electronic device created and designed to catalog and provide information regarding the various species of 
        Pokémon featured in the Pokémon video game, anime and manga series. In the Pokémon continuity, the Pokédex was invented by 
        Professor Oak, a respected professor in the science of Pokémon. Whenever a Pokémon is first captured, its data will be added to a player's Pokédex.
        Feel free to add your Favorite Pokemon! <strong>Happy training Pokemon Masters!</strong></p>
  
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Pokemon</title>
</head>
<body>
    <header>
        <nav>
            <ul class="left">
                <li><a href="{% url 'home' %}"><img src="https://i.imgur.com/KOaRATv.png" height="50px" width="50px"></a></li>
            </ul>
            <ul class="right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'index' %}">POKÉMON</a></li>
                <li id="mid"><a href="{% url 'pokemons_create' %}">CREATE A POKÉMON</a></li>
                <li><a href="{% url 'pokeballs_index' %}">POKÉBALLS</a></li>
                <li><a href="{% url 'pokeballs_create' %}">ADD POKÉBALLS</a></li>
                <li><a href="{% url 'logout' %}">LOG OUT</a></li>
            {% else %}
                <li><a href="{% url 'signup' %}">SIGN UP</a></li>
                <li><a href="{% url 'login' %}">LOG IN</a></li>
            {% endif %}
                <li><a href="{% url 'about' %}">ABOUT</a></li>
            </ul>
        </nav>
    </header>
        {% block content %}
        {% endblock %}
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div id="home">
    <h1 id="homeTitle">POKÉDEX</h1>
   
</div>



{% endblock %}

main_app/templates/main_app/pokeball_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>DELETE POKÉBALL</h1>
<h3>Are you sure you want to delete <strong>{{ object.name }}</strong>?</h3>
<form action="" method="POST" id="deleteId">
    {% csrf_token %}
    <a href="{% url 'pokeballs_detail' object.id %}" id="cancel">Cancel</a>
    <input type="submit" value="delete" id="del" class="btn">
  </form>

{% endblock %}

main_app/templates/main_app/pokeball_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ pokeball.name }}</h1>
    <table>
        <tr>
            <td class="label"> Type: </td>
            <td> {{pokeball.color }} </td>
        </tr>
        <tr>
            <td>
                <a href="{% url 'pokeballs_update' pokeball.id %}" class="detailBtn">EDIT</a>
                <a href="{% url 'pokeballs_delete' pokeball.id %}" class="detailBtn" id="delete">DELETE</a>
            </td>
        </tr>
    </table>

    {% endblock %}

main_app/templates/main_app/pokeball_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>Edit <span>{{object.name}}</span></h1>
{% else %}
<h1>CREATE POKÉBALL</h1>
{% endif %}
<form action="" method="POST" id="pokeballcreate">
    {% csrf_token %} 
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="ADD POKÉBALL" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/pokeball_list.html
{% extends 'base.html' %}
{% block content %}
<h1> POKÉBALLS </h1>
<main>
    {% for pokeball in pokeball_list %}
    <div class="card">
        <a href="{% url 'pokeballs_detail' pokeball.id %}">
            <div class="content">
                <h2 class="card-title">{{ pokeball.name }}</h2>
                <p><strong class="values">Color: </strong> {{ pokeball.color }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</main>
{% endblock %}

main_app/templates/main_app/pokemon_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>DELETE POKÉMON</h1>
<h3>Are you sure you want to delete <strong>{{ object.name }}</strong>?</h3>
<form action="" method="POST" id="deleteId">
    {% csrf_token %}
    <a href="{% url 'detail' pokemon.id %}" id="cancel">Cancel</a>
    <input type="submit" value="delete" id="del" class="btn">
  </form>




{% endblock %}

main_app/templates/main_app/pokemon_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>Edit <span>{{object.name}}</span></h1>
{% else %}
<h1>CREATE POKÉMON</h1>
{% endif %}
<form action="" method="POST">
    {% csrf_token %} 
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="ADD POKEMON" class="btn">
</form>



{% endblock %}

main_app/templates/pokemon/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ pokemon.name }}</h1>
   <!-- Container for the image gallery -->
<div id="container-photo">
    <!-- <a class="prev" onclick="plusSlides(-1)">&#10094;</a> -->

    {% for photo in pokemon.photo_set.all %}
    <img class="mySlides" src="{{photo.url}}" width="250px" height="250px">
    {% empty %}
    <h2>No Photos Uploaded</h2>
    {% endfor %}

    <!-- Next and previous buttons -->
    <!-- <a class="next" onclick="plusSlides(1)">&#10095;</a> -->

</div>
      

    {% if pokemon.photo_set.all %}

    <h3> </h3>
    {% else %}
    <form action="{% url 'add_photo' pokemon.id %}" enctype="multipart/form-data" method="POST" class="photo-form">
        {% csrf_token %}
        <input type="file" name="photo-file" id="choose-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
    </form>

    {% endif %}





    <table>
        <tr>
            <td class="label"> Type: </td>
            <td> {{pokemon.type }} </td>
        </tr>
        <tr>
            <td class="label"> Ability: </td>
            <td> {{pokemon.ability }} </td>
        </tr>
        <tr>
            <td class="label"> Discription: </td>
            <td> {{pokemon.description }} </td>
        </tr>
        {% if user.is_authenticated and pokemon.user.id == user.id %}
        <tr>
            <td>
                <a href="{% url 'pokemons_update' pokemon.id %}" class="detailBtn">EDIT</a>
                <a href="{% url 'pokemons_delete' pokemon.id %}" class="detailBtn" id="delete">DELETE</a>
            </td>
        </tr>
        {% endif %}
    </table>

    <h3>Add Training Session:</h3>
    <div id="training_form">
        <form action="{% url 'add_training' pokemon.id %}" method="POST" id="form">
            {% csrf_token %}
            {{ training_form.as_table }}
            <input type="submit" id="add_training" value="Add Training">
          </form>

          <div id="training">
              <h4>TRAININGS</h4>
              {% for training in pokemon.training_set.all %}
              <p><strong>When: </strong> <br> {{ training}}</p>
              <p><strong>Training Reason: </strong> <br>{{ training.type }}</p>
              {% endfor %}
          </div>
    </div><br>
    <hr>
    <section id="pokeballTemplate">
        <div id="choice">
            <div>
                <h3>{{ pokemon.name }}'s Pokéballs</h3>
                {% if pokemon.pokeballs.count %}
                {% for pokeball in pokemon.pokeballs.all %}
                    <div class="cardP">
                    <div class="card-content">
                        <span class="card-title">
                            <p class="pName">{{ pokeball.name }}</p>
                            <span>{{ pokeball.color }}</span> 
                        </span>
                    </div>
                    </div>
                {% endfor %}
                {% else %}
                <h5>No Pokéballs :(</h5>
                {% endif %}
            </div>
        </div>
        <div id="pokeball">
            <h3 id="hdr">Available Pokéballs</h3>
            <aside>
            {% if pokeballs.count %}
            {% for pokeball in pokeballs.all %}
                <div class="cardP">
                    <div class="card-content">
                        <span class="card-title">
                            <p class="pName">{{ pokeball.name }}</p>
                            <span>{{ pokeball.color }}</span>
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'assoc_pokeball' pokemon.id pokeball.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn">Add</button>
                        </form>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <h5>{{pokemon.name}} Already Has All POKÉBALLS Available</h5>
                {% endif %}
            </aside>
        </div>
    </section>

<script>
let slideIndex = 1;
showSlides(slideIndex);

// Next/previous controls
function plusSlides(n) {
  showSlides(slideIndex += n);
}

// Thumbnail image controls
function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("demo");
  let captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}

</script>

{% endblock %}

main_app/templates/pokemon/index.html
{% extends 'base.html' %}
{% block content %}
<h1>All Pokémon</h1>

<main>
    {% for pokemon in pokemons %}
    <div class="card">
        <a href="{% url 'detail' pokemon.id %}">
            <div class="content">
                <h2 class="card-title">{{ pokemon.name }}</h2>
                <p><strong class="values">Type:</strong> {{ pokemon.type }}</p>
                <p><strong class="values">Ability:</strong> {{ pokemon.ability }}</p>
                <p><strong class="values">Description:</strong> {{ pokemon.description }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</main>



{% endblock %}